title: "Bavalpreet Singh"
description: "Data Scientist & AI/ML Engineer — Conversational AI, GenAI, and NLP"
url: "https://bavalpreet.github.io"
baseurl: ""
markdown: kramdown
timezone: America/Toronto
collections:
  projects:
    output: true